"""Tests for ScipyMLEFitter and its built-in parameter maps."""
# copyright: skpro developers, BSD-3-Clause License (see LICENSE file)

__author__ = ["patelchaitany"]

import inspect

import numpy as np
import pandas as pd
from skbase.testing import QuickTester

from skpro.distfitter import ScipyMLEFitter
from skpro.distfitter._mlefitter import _DEFAULT_FIT_KWARGS, _DEFAULT_PARAM_MAPS
from skpro.tests.test_all_estimators import BaseFixtureGenerator, PackageConfig


def test_default_param_map_spec():
    """Test that every row of the built-in param maps is well formed.

    Each row says how to turn scipy parameter names into skpro ones. This
    checks, for every row, that the distribution exists, that the names on
    the skpro side are real arguments of that distribution, and that the
    transform is one the fitter knows how to apply.

    The rows are read from ``_DEFAULT_PARAM_MAPS`` itself, so a distribution
    added there is checked without editing this test.
    """
    from skpro.registry import all_objects

    dists = dict(all_objects(object_types="distribution", return_names=True))

    assert isinstance(_DEFAULT_PARAM_MAPS, dict)
    assert len(_DEFAULT_PARAM_MAPS) > 0

    for dist_name, param_map in _DEFAULT_PARAM_MAPS.items():
        assert isinstance(param_map, dict)
        assert dist_name in dists, (
            f"{dist_name!r} has a built-in param map but is not a distribution "
            f"in the skpro registry"
        )

        sig = inspect.signature(dists[dist_name].__init__).parameters
        constructor_args = set(sig) - {"self", "index", "columns"}

        unknown = set(param_map) - constructor_args
        assert not unknown, (
            f"param map for {dist_name} maps to {sorted(unknown)}, which are "
            f"not constructor arguments; expected a subset of "
            f"{sorted(constructor_args)}"
        )

        for skpro_name, entry in param_map.items():
            assert isinstance(entry, tuple) and len(entry) == 2, (
                f"param map entry {dist_name}.{skpro_name} must be a "
                f"(scipy_key, transform) pair, got {entry!r}"
            )
            scipy_key, transform = entry
            assert isinstance(scipy_key, str)
            assert transform in ["identity", "inverse"], (
                f"param map entry {dist_name}.{skpro_name} uses unknown "
                f"transform {transform!r}"
            )


def test_default_param_map_does_not_discard_fitted_params():
    """Test that no fitted parameter is estimated and then thrown away.

    scipy always estimates ``loc`` and ``scale`` on top of the shape
    parameters, but many skpro distributions have nowhere to put them. Each
    of the two must therefore either be used by the param map, or be held
    fixed during the fit via ``floc`` or ``fscale``.

    If it is neither, scipy estimates it from the data and the param map then
    drops it, so the distribution that comes back is not the one that was
    fitted, and nothing reports an error.
    """
    for dist_name, param_map in _DEFAULT_PARAM_MAPS.items():
        mapped = {scipy_key for scipy_key, _ in param_map.values()}
        fit_kwargs = _DEFAULT_FIT_KWARGS.get(dist_name, {})

        for param, fix in [("loc", "floc"), ("scale", "fscale")]:
            assert param in mapped or fix in fit_kwargs, (
                f"param map for {dist_name} does not use scipy {param!r}, and "
                f"_DEFAULT_FIT_KWARGS does not pin it via {fix!r}; the fitted "
                f"{param} would be estimated and then discarded"
            )


class ScipyMLEFitterFixtureGenerator(BaseFixtureGenerator):
    """Fixture generator for the scipy backed maximum likelihood fitter.

    Fixtures parameterized
    ----------------------
    object_class: object inheriting from BaseObject
        ranges over object classes not excluded by EXCLUDE_OBJECTS, EXCLUDED_TESTS
    object_instance: instance of object inheriting from BaseObject
        ranges over object classes not excluded by EXCLUDE_OBJECTS, EXCLUDED_TESTS
        instances are generated by create_test_instance class method
    """

    object_type_filter = ScipyMLEFitter


class TestScipyMLEFitter(PackageConfig, ScipyMLEFitterFixtureGenerator, QuickTester):
    """Tests specific to the scipy backed maximum likelihood fitter."""

    def test_param_map_agrees_with_scipy(self, object_instance):
        """Test that the fitter returns the same distribution scipy fitted.

        The same data is fitted twice, once through the fitter and once
        through scipy directly, using the scipy distribution and fit options
        the fitter itself chose. Both sides therefore do the same estimation,
        and the only step that differs is the translation of parameter names.
        Any disagreement is that translation.

        This is needed because a row that points at the wrong scipy parameter,
        or that uses ``"identity"`` where it needs ``"inverse"``, still fits
        without error and still returns a sensible looking distribution. The
        numbers are simply wrong.

        The two sides are compared through the cdf, not the parameters,
        because they use different parameter names on purpose, so the numbers
        are not comparable directly. The comparison points are quantiles of
        the fitted distribution, which puts them where the distribution has
        its mass, and works for distributions with no mean or variance.
        """
        fitter = object_instance

        X = pd.DataFrame(np.abs(np.random.RandomState(42).randn(50, 1)) + 0.5)
        fitter.fit(X)
        dist = fitter.proba()

        # repeat the fit on the scipy side, using the fitter's own resolved
        # backend and kwargs, so that only the parameter translation differs
        _, fit_kwargs, scipy_obj = fitter._resolve_defaults()
        scipy_result = scipy_obj.fit(X.values.ravel(), **fit_kwargs)
        scipy_params = ScipyMLEFitter._fit_result_to_dict(scipy_obj, scipy_result)

        shapes = scipy_obj.shapes or ""
        shape_args = [scipy_params[s.strip()] for s in shapes.split(",") if s.strip()]

        for q in [0.1, 0.5, 0.9]:
            x = float(dist.ppf(q))
            assert np.isfinite(x), f"ppf({q}) is not finite: {x}"

            skpro_cdf = float(dist.cdf(x))
            scipy_cdf = float(
                scipy_obj.cdf(
                    x,
                    *shape_args,
                    loc=scipy_params["loc"],
                    scale=scipy_params["scale"],
                )
            )

            assert np.isclose(skpro_cdf, scipy_cdf, atol=1e-6), (
                f"cdf at the {q} quantile is {skpro_cdf} in skpro but "
                f"{scipy_cdf} in scipy; the param map translates to the wrong "
                f"scipy parameter, or applies the wrong transform"
            )
