# copyright: skpro developers, BSD-3-Clause License (see LICENSE file)
"""Zero-inflated Poisson probability distribution."""

__author__ = ["Mutalenic"]

from functools import cached_property

import pandas as pd
from numpy.typing import ArrayLike

from skpro.distributions.base import BaseDistribution


class ZeroInflatedPoisson(BaseDistribution):
    r"""Zero-Inflated Poisson distribution.

    A convenience wrapper around ``ZeroInflated(Poisson(mu), p=p)``.

    The distribution is a mixture of a point mass at zero and a Poisson
    distribution:

    .. math::
        Y = \begin{cases}
              0 &\text{ with probability } 1 - p, \\
              X \sim \mathrm{Poisson}(\mu) &\text{ with probability } p.
            \end{cases}

    Parameters
    ----------
    mu : float or array of float (1D or 2D)
        Mean of the Poisson component.
    p : float or array of float (1D or 2D)
        Probability that the outcome is generated by the Poisson component
        (i.e., ``1 - p`` is the probability of a structural zero).
    index : pd.Index, optional, default = RangeIndex
    columns : pd.Index, optional, default = RangeIndex

    Examples
    --------
    >>> from skpro.distributions import ZeroInflatedPoisson
    >>>
    >>> distr = ZeroInflatedPoisson(mu=2.0, p=0.7)
    >>> samples = distr.sample(5)
    """

    _tags = {
        # packaging info
        # --------------
        "authors": ["Mutalenic"],
        # estimator tags
        # --------------
        "capabilities:approx": ["energy"],
        "capabilities:exact": ["ppf", "mean", "var", "log_pmf", "pmf", "cdf"],
        "distr:measuretype": "discrete",
        "distr:paramtype": "parametric",
        "broadcast_init": "on",
        "broadcast_params": ["mu", "p"],
    }

    def __init__(
        self,
        mu: ArrayLike,
        p: ArrayLike,
        index=None,
        columns=None,
    ):
        self.mu = mu
        self.p = p

        super().__init__(index=index, columns=columns)

    @cached_property
    def _zi(self):
        """Construct the inner ZeroInflated(Poisson) delegate on the fly."""
        from skpro.distributions.poisson import Poisson
        from skpro.distributions.zeroinflated import ZeroInflated

        base = Poisson(mu=self._bc_params["mu"], index=self.index, columns=self.columns)
        return ZeroInflated(
            p=self._bc_params["p"],
            distribution=base,
            index=self.index,
            columns=self.columns,
        )

    def _log_pmf(self, x):
        return self._zi._log_pmf(x)

    def _pmf(self, x):
        return self._zi._pmf(x)

    def _cdf(self, x):
        return self._zi._cdf(x)

    def _ppf(self, p):
        return self._zi._ppf(p)

    def _mean(self):
        return self._zi._mean()

    def _var(self):
        return self._zi._var()

    @classmethod
    def get_test_params(cls, parameter_set="default"):
        """Return testing parameter settings for the estimator."""
        params1 = {"mu": 2.0, "p": 0.7}
        params2 = {
            "mu": [[1, 1], [2, 3], [4, 5]],
            "p": 0.4,
            "index": pd.Index([1, 2, 5]),
            "columns": pd.Index(["a", "b"]),
        }
        params3 = {
            "mu": [[1, 2, 3], [4, 5, 6]],
            "p": [[0.3, 0.3, 0.3], [0.5, 0.5, 0.5]],
            "index": pd.Index([0, 1]),
            "columns": pd.Index(["a", "b", "c"]),
        }
        return [params1, params2, params3]
