# copyright: skpro developers, BSD-3-Clause License (see LICENSE file)
"""Zero-Inflated Negative Binomial probability distribution."""

import pandas as pd
from numpy.typing import ArrayLike

from skpro.distributions.base import BaseDistribution


class ZINB(BaseDistribution):
    r"""Zero-Inflated Negative Binomial distribution.

    Combines a Bernoulli gate for structural zeros with a Negative Binomial
    distribution. Equivalent to
    ``ZeroInflated(p=p, distribution=NegativeBinomial(mu=mu, alpha=alpha))``.
    Parameters
    ----------
    p : float or array of float (1D or 2D)
        Probability of the outcome being generated by the NB component.
    mu : float or array of float (1D or 2D)
        Mean of the Negative Binomial distribution.
    alpha : float or array of float (1D or 2D)
        Dispersion parameter of the Negative Binomial distribution.
    index : pd.Index, optional, default = RangeIndex
    columns : pd.Index, optional, default = RangeIndex

    Examples
    --------
    >>> from skpro.distributions import ZINB

    >>> distr = ZINB(p=0.7, mu=2.0, alpha=1.0)
    >>> distr.mean()
    1.4
    """

    _tags = {
        # packaging info
        # --------------
        "authors": ["MurtuzaShaikh26"],
        # estimator tags
        # --------------
        "capabilities:approx": ["energy"],
        "capabilities:exact": ["mean", "var", "pmf", "log_pmf", "cdf", "ppf"],
        "distr:measuretype": "discrete",
        "distr:paramtype": "parametric",
        "broadcast_init": "on",
    }

    def __init__(
        self,
        p: ArrayLike,
        mu: ArrayLike,
        alpha: ArrayLike,
        index=None,
        columns=None,
    ):
        self.p = p
        self.mu = mu
        self.alpha = alpha

        super().__init__(index=index, columns=columns)

    @property
    def _zi(self):
        """Construct the delegate ZeroInflated(NegativeBinomial)."""
        from skpro.distributions.negative_binomial import NegativeBinomial
        from skpro.distributions.zeroinflated import ZeroInflated

        base = NegativeBinomial(
            mu=self.mu, alpha=self.alpha, index=self.index, columns=self.columns
        )
        return ZeroInflated(
            p=self.p,
            distribution=base,
            index=self.index,
            columns=self.columns,
        )

    def _pmf(self, x):
        return self._zi.pmf(x)

    def _log_pmf(self, x):
        return self._zi.log_pmf(x)

    def _cdf(self, x):
        return self._zi.cdf(x)

    def _ppf(self, p):
        return self._zi.ppf(p)

    def _mean(self):
        return self._zi.mean()

    def _var(self):
        return self._zi.var()

    @classmethod
    def get_test_params(cls, parameter_set="default"):
        """Return testing parameter settings for the estimator."""
        params1 = {"p": 0.7, "mu": [[1, 1], [2, 3], [4, 5]], "alpha": 2.0}
        params2 = {
            "p": 0.3,
            "mu": 1.0,
            "alpha": 2.0,
            "index": pd.Index([1, 2, 5]),
            "columns": pd.Index(["a", "b"]),
        }
        return [params1, params2]
