# copyright: skpro developers, BSD-3-Clause License (see LICENSE file)
"""Zero-Inflated Poisson probability distribution."""

import pandas as pd
from numpy.typing import ArrayLike

from skpro.distributions.base import BaseDistribution


class ZIPoisson(BaseDistribution):
    r"""Zero-Inflated Poisson distribution.

    Combines a Bernoulli gate for structural zeros with a Poisson distribution.
    Equivalent to ``ZeroInflated(p=p, distribution=Poisson(mu=mu))``.

    .. math::
        Y = \begin{cases}
                0 &\text{ with probability } 1 - p, \\
                X \sim \text{Poisson}(\mu) &\text{ with probability } p,
        \end{cases}

    Parameters
    ----------
    p : float or array of float (1D or 2D)
        Probability of the outcome being generated by the Poisson component.
    mu : float or array of float (1D or 2D)
        Mean of the Poisson distribution.
    index : pd.Index, optional, default = RangeIndex
    columns : pd.Index, optional, default = RangeIndex

    Examples
    --------
    >>> from skpro.distributions import ZIPoisson

    >>> distr = ZIPoisson(p=0.7, mu=2.0)
    >>> distr.mean()
    1.4
    """

    _tags = {
        # packaging info
        # --------------
        "authors": ["MurtuzaShaikh26"],
        # estimator tags
        # --------------
        "capabilities:approx": ["energy"],
        "capabilities:exact": ["mean", "var", "pmf", "log_pmf", "cdf", "ppf"],
        "distr:measuretype": "discrete",
        "distr:paramtype": "parametric",
        "broadcast_init": "on",
    }

    def __init__(
        self,
        p: ArrayLike,
        mu: ArrayLike,
        index=None,
        columns=None,
    ):
        self.p = p
        self.mu = mu

        super().__init__(index=index, columns=columns)

    @property
    def _zi(self):
        """Construct the delegate ZeroInflated(Poisson) on the fly."""
        from skpro.distributions.poisson import Poisson
        from skpro.distributions.zeroinflated import ZeroInflated

        base = Poisson(mu=self.mu, index=self.index, columns=self.columns)
        return ZeroInflated(
            p=self.p,
            distribution=base,
            index=self.index,
            columns=self.columns,
        )

    def _pmf(self, x):
        return self._zi.pmf(x)

    def _log_pmf(self, x):
        return self._zi.log_pmf(x)

    def _cdf(self, x):
        return self._zi.cdf(x)

    def _ppf(self, p):
        return self._zi.ppf(p)

    def _mean(self):
        return self._zi.mean()

    def _var(self):
        return self._zi.var()

    @classmethod
    def get_test_params(cls, parameter_set="default"):
        """Return testing parameter settings for the estimator."""
        params1 = {"p": 0.7, "mu": [[1, 1], [2, 3], [4, 5]]}
        params2 = {
            "p": 0.3,
            "mu": 2.0,
            "index": pd.Index([1, 2, 5]),
            "columns": pd.Index(["a", "b"]),
        }
        return [params1, params2]
